### PR TITLE
Fix missing tincanlaunch:addinstance translation token

### PR DESCRIPTION
**Pull request by nadavkav**
Minor translation fix

### CODE REVIEW

**Comment by garemoko** [comment]
Thanks for this. Where does this text appear? Do you mind using "Tin Can" instead of "tincan"?

**Comment by nadavkav** [comment]
Sure. changed the Tin Can text.

When I turn debugging on, I can see it on the Teacher role editing page (or any other Role) when viewing: Home / ► Site administration / ► Users / ► Permissions / ► Define roles

**Comment by garemoko** [comment]
Ok great. This looks good to me. I'd like somebody other than @nadavkav to install this and test on their Moodle before I merge, but I'd be surprised if there's any issue. I'll merge once that's done and may be able to get some time to test myself.

**Comment by garemoko** [comment]
Sorry this has taken so long to merge. I'm planning to test this today.

**Pull request merged**
