### PR TITLE
Tradução Português Brasil pt-BR

### PR DESCRIPTION
**Pull request by kelvinsleonardo**

### CODE REVIEW

**Comment by garemoko** [comment]
Hi Kelvin, 

You don't need to keep opening new PRs - just add commits to the branch. 

Andrew

**Comment by garemoko** [comment]
You can ignore the error "Variable "http_response_header" must not contain underscores."

That's a bug in the tests that should be resolved when the Moodle team do their next release.

**Comment by kelvinsleonardo** [comment]
Hi Andrew, ok

But not working

[image: Imagem inline 1]
[image: Imagem inline 2]

2016-06-24 14:34 GMT-03:00 Andrew Downes notifications@github.com:

> Hi Kelvin,
> 
> You don't need to keep opening new PRs - just add commits to the branch.
> 
> Andrew
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/garemoko/moodle-mod_tincanlaunch/pull/106#issuecomment-228409997,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHfYzst6dZshvf2CEg7KsrekUgvNfs-cks5qPBUwgaJpZM4I995o
> .

## 

Kélvin Santiago Leonardo
Analista Desenvolvedor Java

---

Email: kelvinsleonardo@gmail.com | Skype: kelvinsleonardo | Site:
http://www.kelvinsantiago.com.br

**Comment by kelvinsleonardo** [comment]
ok, Andrew, change folder "pt" to "pt_br".

2016-06-24 14:36 GMT-03:00 Kélvin Santiago kelvinsleonardo@gmail.com:

> Hi Andrew, ok
> 
> But not working
> 
> [image: Imagem inline 1]
> [image: Imagem inline 2]
> 
> 2016-06-24 14:34 GMT-03:00 Andrew Downes notifications@github.com:
> 
> > Hi Kelvin,
> > 
> > You don't need to keep opening new PRs - just add commits to the branch.
> > 
> > Andrew
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/garemoko/moodle-mod_tincanlaunch/pull/106#issuecomment-228409997,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AHfYzst6dZshvf2CEg7KsrekUgvNfs-cks5qPBUwgaJpZM4I995o
> > .
> 
> ## 
> 
> Kélvin Santiago Leonardo
> Analista Desenvolvedor Java
> 
> ---
> 
> Email: kelvinsleonardo@gmail.com | Skype: kelvinsleonardo | Site:
> http://www.kelvinsantiago.com.br

## 

Kélvin Santiago Leonardo
Analista Desenvolvedor Java

---

Email: kelvinsleonardo@gmail.com | Skype: kelvinsleonardo | Site:
http://www.kelvinsantiago.com.br

**Comment by garemoko** [comment]
I've duplicated the folder so that any Portuguese Portuguese speakers can edit that original version.

**Comment by kelvinsleonardo** [comment]
Perfect, tks

2016-06-24 15:05 GMT-03:00 Andrew Downes notifications@github.com:

> I've duplicated the folder so that any Portuguese Portuguese speakers can
> edit that original version.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/garemoko/moodle-mod_tincanlaunch/pull/106#issuecomment-228417782,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHfYzt6Ub-lH9nTkHGMcrTJbV8ba5K_Tks5qPBxogaJpZM4I995o
> .

## 

Kélvin Santiago Leonardo
Analista Desenvolvedor Java

---

Email: kelvinsleonardo@gmail.com | Skype: kelvinsleonardo | Site:
http://www.kelvinsantiago.com.br

**Pull request merged**
