### PR TITLE
Mask password field in launch form

### PR DESCRIPTION
**Pull request by nadavkav**
I have used "passwordunmask" because I thought it would be nice to enable the user to see his/her password. But, for better security you might just use "password".

What do you think?

### CODE REVIEW

**Comment by garemoko** [comment]
This looks sensible. I'll check it out later. It should also apply to the username field too.

**Comment by nadavkav** [comment]
Great.

**Comment by garemoko** [comment]
Hi, I've tested this out and it works, but having thought about this, I don't think it adds any additional security. Chances are people will copy and paste these values from their LRS anyway which is in plain text, and the encoded authorisation key is visible in the querystring anyway. 

On the negative side. it could add a false sense of security or be annoying. 

So on balance, I think I'll leave this one out. 

Thanks for contributing though. Please do keep making suggestions and contributions.

**Comment by nadavkav** [comment]
You are right. (It was an old habit)

BTW, please have a look of a new feature I suggested to the mod/lti module
https://tracker.moodle.org/browse/MDL-40899
It might be useful to add some kind of an admin setting for adding predefined Tincan activities.
What do you think?

**Pull request closed without merging**
