### PR TITLE
Removed redundant admin setting for duration.

### PR DESCRIPTION
**Pull request by davidpesce**
Removed redundant declaration for duration admin setting.

### CODE REVIEW

**Comment by davidpesce** [comment]
This shouldn't impact @nadavkav's latest pull request.

**Comment by garemoko** [comment]
This setting isn't redundant! (or at least it's not supposed to be!)

It should be used as the default duration for each module so that you can specify it centrally and then not have to worry about entering it each time for new modules.

**Comment by davidpesce** [comment]
Thanks, @scara! This will help me in my quest to understand Moodle plugins. I don't think it's necessary though. I'm still learning, so correct me if I'm wrong, but here's my thinking.

There are two declarations for LRS Duration within the Admin Settings (settings.php). They are identical. I simply removed the second declaration. Those are stored in a generic moodle config database table (mdl_config_plugins). There isn't a second "lrsduration" row within that table. So I shouldn't need to remove it via an upgrade, correct?

@garemoko While duration is visible when adding the activity (mod_form.php), it is not set within the mdl_tincanlaunch database table, nor updated. It is simply pulled from the global admin setting. The same goes for the hidden form fields you have for lrsendpoint, auth, etc. One of the things I'm working on is an upgrade xml file that will actually store the "global" settings in the mdl_launch settings for each activity so that additional LRS(s) can be specified via an advanced setting. Basically a "uncheck if you don't want to inherit your global settings."

Thoughts?

**Comment by garemoko** [comment]
Oooh I see! Sorry. Merged!

It will definitely be helpful to specific different/additional LRS at an activity level, though this should be hidden within the advanced settings.

**Comment by scara** [comment]
@davidpesce: correct! I didn't read your comment (apologies) but just seen the PR... removing a setting w/o removing it from the DB too triggered my (wrong as per the actual context) peer review :blush:.

**Comment by davidpesce** [comment]
@garemoko No worries. I'm just glad I'm understanding it better!

@scara Aye, but I learned something new today.Thank you!

**Comment by nadavkav** [comment]
It seems to me that we better use Moodle's internal cron to timely check for user's activity completion.
Maybe...
Every 10min, run an internal check on what activities that were started and to which we do not have a completion yet for its students. and for those who are missing activity completion run an external LRS query that is specific for that activity id and that specific "completed/passed/finished" verb. (to lessen the network traffic and load on the LMS and LRS servers)

Ideally, the LRS will send (maybe forward) a "completed" message to Moodle's LRS (if one is installed) and an event observer could mark the activity completed or/and we should implement within this module so it could be able to accept a single completed verb (yes, a wild idea)

I think the whole concept is a little problematic. and not properly addressed in the xAPI specs, and that we should consider implementing CMI-5 concepts like: https://github.com/AICC/CMI-5_Spec_Current/blob/master/cmi5_runtime.md#last_statement_au

**Comment by davidpesce** [comment]
@nadavkav I think this was meant for the other PR. Maybe?

**Pull request merged**
