### PR TITLE
Watershed integration

### PR DESCRIPTION
**Pull request by garemoko**
Create a fresh AP for each launch in Watershed. Rename "integrated LRS basic auth" to "Learning Locker integration".

This is still under development but comments and tests are welcome. Still to do:

Delete the created AP credentials after X minutes (duration setting).

### CODE REVIEW

**Comment by garemoko** [comment]
This is now complete, but I need to test as a fresh install and as an upgrade to the latest release.

Volunteers to check that I haven't broken the Learning Locker integration whilst building this Watershed integration are very welcome @nadavkav @davidpesce

**Comment by nadavkav** [comment]
Yes please :-) and with some urgency, as tomorrow I am demonstrating to the entire academic IT from all the Israeli education sector, several xAPI solutions. and I would really LOVE to show Watershed's UI and features.

Can you set me up with a Watershed demo account?

**Comment by garemoko** [comment]
@nadavkav sure. I will send an email to your gmail account. Thank you!

**Comment by davidpesce** [comment]
Count me in for testing too!

**Comment by garemoko** [comment]
@davidpesce Thanks! Check your inbox!

**Comment by garemoko** [comment]
Tested from a fresh install and works great.

**Comment by garemoko** [comment]
Bug discovered when testing upgrade: if you edit the default settings, Watershed credentials are not created for instances that use default settings.

**Comment by garemoko** [comment]
Now when you make a change to the default settings, the plugin will go and update the instance settings for all instances that use the defaults, including creating Watershed credentials as needed.

**Comment by garemoko** [comment]
I'm going to leave this open for 1 week for you guys to test and review, then I'll merge.

**Comment by davidpesce** [comment]
Hold off on merging. This bricked my new Moodle (Build: 20160218) install. Still trying to figure out where it went wrong.

**Comment by davidpesce** [comment]
Still unsure what is going on. After installing the plugin, I get a completely blank page from Moodle. The url is:

```
'domain/admin/index.php?cache=1' 
```

I deleted the plugin from the filesystem and Moodle does the plugin upgrade database routine and all is fine. Attempting to install again and got the same results. Turned on developer debugging and plugin validation passes before install.

Maybe it's too new of a Moodle version? Maybe there's an issue with this Moodle release?

**Comment by davidpesce** [comment]
User error. I didn't pull down the TinCanPHP and WatershedPHP repos to include in the plugin zip.

**Comment by garemoko** [comment]
@davidpesce ah yes, I've done that a couple of times. When I publish to the plugins directory, I'll make sure those are included.

**Comment by garemoko** [comment]
from @davidpesce "Something that was odd. When attempting to set the global tincanlaunch plugin settings. I was getting the 401 unauthorized when adjusting all the settings at once. If I left it as None and set the email/pw, saved, then set to Watershed, I didn't get the error. And all was well."

I suspect the credential refresh event is triggering before all the fields have updated. Need to figure out how to only trigger on the last one.

**Comment by garemoko** [comment]
I think I'm going to fix this by adding a "update activity instances" checkbox and triggering off that instead of from the various settings that might change.

**Comment by davidpesce** [comment]
Shouldn't the activity instances inherit from the global (unless overridden)? The plugin shouldn't need to update activity instances.

**Comment by garemoko** [comment]
@davidpesce For the Watershed integration I have the plugin set up to create a set of master credentials for each instance of the plugin in order to give more granular authority information. For that reason even instances that use the global defaults still need their own settings. 

That said, maybe that's overkill and one set of credentials for server side tracking of all instances that use the defaults would be sufficient, especially since this approach is causing problems. On the other hand, I think i'll actually hit the same difficulty in triggering the  generation and update of global credentials.The global settings don't have an updated function I can hook into like the instance settings. I'll take another look at the code and see what i can figure out.

**Comment by garemoko** [comment]
Hm, this is trickier than I thought. I just can;t find a way to trigger some code on setting submission that is sure to run after all settings have been updated in the database. Alternative approach is to check every time I go to use credentials if it's a watershed integration and if watershed credentials have been generated, but I don't like to put the watershed integration that deep.

**Comment by davidpesce** [comment]
Maybe it's worth putting in the cron? Moodle's recommended interval is every minute. Granted not everyone has that.

**Comment by garemoko** [comment]
@davidpesce yeh, I considered that. I just don't like the gap. Though i guess they'd continue to use the old settings until cron ran and they could force an update for a particular module by editing the settings perhaps. It's the best option at the moment by virtue of being the only option.

**Comment by garemoko** [comment]
I'd have to change the activity module so that it always clones the defaults so that it keeps those saved until cron runs to sort things out properly. - Not ideal at all.

**Comment by garemoko** [comment]
@davidpesce that should fix the issue. I'm now not updating instance level watershed credentials at the point the global settings are updated; instead, when module settings are requested in tincanlaunch_settings, I'm checking if watershed credentials are up to date (or even present) and refreshing if not. 

I'm also now caching the settings as a global variable so that we only pull them from the database once per page. This was to avoid a problem where credentials were getting created multiple times because they hadn't been stored in the database by the time the code checked if they were there a second time. It should also reduce DB queries overall, which is good. 

The other thing I changed is that use_global_lrs_settings now checks the tincanlaunch table for a tick in the overridedefaults box rather than checking to see if instance settings exist in the tincanlaunch_lrs table. I think that's a better approach generally.

**Comment by davidpesce** [comment]
I like it!

**Comment by davidpesce** [comment]
@garemoko will any of these changes be merged back into master?

**Comment by garemoko** [comment]
@davidpesce yes, today most likely. I wanted to allow @nadavkav some time to respond too.

**Comment by nadavkav** [comment]
Just now found the time to test this a little bit.
One thing I noticed is that I was getting "401 unauthorized" which was only gone by setting LRS integration to None.
I am still playing around with it and also getting to know the watershedlrs sandbox features. so it all looks very good and potentially interesting. sweet!

**Comment by nadavkav** [comment]
As I was testing this on an old version of tincanlaunch I needed to upgrade it too, and while upgrading that old version i got some errors that were fix with the following patch: https://github.com/garemoko/moodle-mod_tincanlaunch/pull/92

**Comment by garemoko** [comment]
@nadavkav did you have your watershed username and password entered?

**Comment by nadavkav** [comment]
The ones I use to login into WS?

**Comment by garemoko** [comment]
@nadavkav yep. Use the same ones in the plugin. Be aware that the password is stored in the Moodle database so choose a password carefully. In real situations we'd create an account specifically for the Moodle itself.

**Comment by nadavkav** [comment]
Just now tested and it works fine.

**Comment by garemoko** [comment]
Thanks!

**Pull request merged**
