### PR TITLE
Text fixes for PR44

### PR DESCRIPTION
**Pull request by davidpesce**
Addresses text changes needed after PR #44 and directly addresses #55.

### CODE REVIEW

**Comment by garemoko** [comment]
Not tested; but the code looks good. As soon as I or somebody else gets time to test this I'll merge.

**Comment by garemoko** [comment]
Merged into development branch (newly created). Will merge into master once development has been tested. Please make future PRs to the new development branch and I'll merge after discussion and code review; we can do testing altogether before merging into master. Please do continue to self test all code before making a PR.

**Comment by garemoko** [comment]
Testing the development branch including your three open PRs, I get a string of errors on moodle/admin/upgradesettings.php when I replace my version of the plugin with this one. Further, it's telling me that i have a new setting called `[[tincanlaunchlrsauthentication]]` and it is not pulling in language strings for any of the options. 

Note that I didn't have time to reset my plugin to master and then try and upgrade to development. Can you try the development branch after you uninstall and re-install the master, and then let me know whether you see this issue? If not, I'll uninstall and re-install master myself and try again.  

I've not progressed further with the testing as it's clearly broken (on my laptop at least).

**Comment by davidpesce** [comment]
I think it may in fact be an issue. I haven't tested it yet. But the correctly spelled tincanlaunchlrsauthentication configuration setting isn't set in the upgrade.php file. I think I had already saved my settings and then did the unset_config.

I'll test it and see.

**Comment by davidpesce** [comment]
Catching back up on this...

I did a fresh install of Master and then an upgrade to Development. Interestingly enough, it worked flawlessly. Moodle automatically detected that an admin setting had changed and required that I select a global LRS authentication. 

This should be good to go to merge into master.

**Pull request merged**
