### PR TITLE
Fix for issue #19 - plugin settings have no help.

### PR DESCRIPTION
**Pull request by davidpesce**
Fixes for issue #19. Includes some code-formatting and grouping of lang strings for readability.

### CODE REVIEW

**Comment by davidpesce** [comment]
Should also resolve the default settings issue #30

**Comment by garemoko** [comment]
Thanks for this @davidpesce!

A few comments of feedback if you don't mind:
- The duration field from the main module settings is pulling through to existing instances. It should be used as a default for new instances.
- The verb id in the completion settings reverts to an empty field if you save the activity without completion tracking. It should default back to the completed verb if you then enable tracking based on conditions again. 
- We should increment the version and build number in version.php

It may be that these issues are already present in the current module, but it'd be great if you can fix them as part of this PR so we can get the two issues you aimed to resolve resolved. Is that ok?

**Comment by davidpesce** [comment]
I'll have to do more research on the completion issue, but the other two are part of what I'm working on. My ultimate goal is to implement the ability to set global defaults and then override them as advanced settings in each activity. This is a step in that direction, but I didn't want to get too far behind with @nadavkav PR.

Right now, regardless of what you put in the duration field (at the activity level), it will pull the default from the admin module settings. There is no duration row within the mdl_tincanlaunch table, so it is never stored. 

With the (future) ability to override admin module setting (defaults) in each activity, should the duration be an override-able field?

**Comment by nadavkav** [comment]
Regarding @garemoko second point:
We always need the completion verb set for testing that the activity was completed regardless of using Moodle's completion mechanism.

And to make it even more complicated... different content authoring applications use different "completion" verbs ("completed", "finished", "passed" ... ) and it seems we should (somehow) get that verb from the specific activity that is monitored for its completion statues.

Until there is some consensus on the completed verb we should display a list of verbs (maybe with content authoring system names along side the verbs) to enable the teacher to choose what is appropriate for the activity he/she is using.

All of the above is considered when we are not manually sending from Moodle the "completion" verb when the user click "continue to course" link. (which I can not trust. since they might click some other navigation link or the JS could fail due to other 3rd party JS error on the page)

**Comment by garemoko** [comment]
Yeh, duration should be overridable IMHO. Basically it depends on how long it will take the user to complete the activity so could vary on an activity basis. Equally, less-security concerned systems will have duration set to a longer value globally. 

@nadavkav right - that's why it's customisable. I'm just saying that it should default to something sensible (which it does normally, just not when you follow the particular set of steps I outlined).

**Comment by davidpesce** [comment]
Here's what the new activity settings looks like:

Imgur

Clicking the override defaults checkbox allows editing of the greyed-out advanced settings.

Thoughts?

**Comment by davidpesce** [comment]
I'm wondering if my choice of "Override defaults" is appropriate. Thoughts?

**Comment by nadavkav** [comment]
@davidpesce your new activity setting looks great.
though I have some ideas for modifications:
- I am about to upload a patch that retrieve the activityid from the tincan.xml using the launch url (removing the launch file, if one is added) so I guess the activityid might be redundant after this patch.
- Duration label should be more clear to the end user : "Duration (in Minutes)"
- Display a note (label element) in the advanced section that directs the user to the Completion section for setting a completion verb. Or have a setting for it in the advanced section which automatically affect (changes) the one in the completion section. (Since Moodle teachers might not mentally link between  Moodle's activities completion feature and xAPI's completion verb. Many teachers have this mechanism off by default or are not familiar with it)

**Comment by garemoko** [comment]
Looks nice! Maybe "Unlock defaults" might be more friendly. 

I disagree with removing the activity id setting as this will be important for many users who do not want to faff around with tincan.xml files; indeed, many activities may not have a tincan.xml file and requiring people to create one for Moodle is silly. The tincan.xml should populate the launch and activity id fields, sure, but they should continue to be editable. 

Agree that Duration should have (mins) in this view as the help text is hidden. 

Disagree on moving the completion verb setting. If the administrator doesn't use Moodle's completion tracking, then this setting is pointless anyway.

**Comment by nadavkav** [comment]
I thought tincan.xml is a must in any xAPI activity, Is it not?
I could add an AJAX call to retrieve the list of activity names and IDs from the tincan.xml file after the user "lost focus" of the activity launch url field, And populate a listbox with names of activities inside the "package" instead of using "scary" activityid. Or/And populate an activityid field with what was choosen by the user from the list of activity names (just above it) ?

Moodle's completion mechanism is for Moodle's internal activities and not for remote xAPI activities. You are mixing similar ideas. They are not the same.

The mod_tincanlaunch module should always look for some kind of activity completion verb inside the LRS that is used by the activity. so the teacher knows where the student is. (Even if Moodle's activity completion is not used)

Here are some screen shoots of work-in-progress grade page for the activity:
image
And after clicking "more details" ...
image
( I will make the verbs look nicer and the activityids show correct names too )

**Comment by garemoko** [comment]
This looks nice! You might consider using the open source JavaScript statement viewer here: https://github.com/RusticiSoftware/TinCanStatementViewer or at least looking at it for reference. 

Moodle's completion tracking is for tracking activities it launches, which is the case here. In fact, I'd love to see Tin Can statements being available to mark ANY Moodle activity as complete. See my comments [here](https://tracker.moodle.org/browse/MDL-35433?focusedCommentId=344969&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-344969).

I can see the case for also having a setting for completion verb in reporting settings, but this should be part of the report filters (maybe a drop-down based on verbs actually used by the activity) rather than activity settings. 

We do need to be careful about replicating reporting features in the LRS, but the kind of simple activity specific reporting you have here is very appropriate.

**Comment by garemoko** [comment]
@davidpesce how's this looking right now? is it in a merge-able (bug free) state?

**Comment by davidpesce** [comment]
Sorry for the delay in getting back. It's definitely not ready yet. 

The first commit for this PR does fix the #19 issue, but I started adding commits for other issues as well.

**Comment by davidpesce** [comment]
@garemoko OK, this is ready!

Fixes #46 & #30

**Comment by garemoko** [comment]
I will take a look at this sometime soon, but an initial comment is that this can't automatically be merged. 

If you're able to, can you look at rebasing your commits from the current version of the repo and resolving the conflict? This can be a little tricky, so if you do get stuck I will fix it for you at some point!

Replacing your version.php with the latest one from the repo might be a good start.

**Comment by davidpesce** [comment]
Good to go!

It looks like version.php was the only merge conflict (luckily). I'm wondering if, in the future, we should follow a model like [this](http://nvie.com/posts/a-successful-git-branching-model/).

I'll do a test of this in an existing install as well as a new install. But it should be ready for your merge/testing as well.

Oh, something to think about, I don't believe we've updated the release version. The above model may help us determine when/if that should happen.

**Comment by davidpesce** [comment]
I think we do need to leave the TC version within the settings. I didn't remove instances of version, but did set the version to 1.0.0 in instances where the global lrs settings were overridden.

1.0.0 works both on LL and SCORMCloud. 1.0.2 does not work for SCORMCloud, but does work for LL.

Other than that, the merge of upstream on an existing install of tincanlaunch and a fresh install works!

Based on your thoughts (on the above version issue), I can make the necessary changes and commit today.

**Comment by davidpesce** [comment]
@nadavkav any chance you're around to test this?

**Comment by garemoko** [comment]
What's the reason for including the version setting? I can't see where it's used that we wouldn't want to hard code as 1.0.2.

Do you get any particular error with SCORM Cloud when setting the version as 1.0.2? I'd like to report this to the team.

**Comment by garemoko** [comment]
On reflection, we should use "1.0.0" for ease of use - there's no practical benefit to specifying "1.0.2".

**Comment by davidpesce** [comment]
I get a php warning:

```
Warning: fopen(https://cloud.scorm.com/tc/scrubbed/activities/state?activityId=http://scrubbed/tc_golf/index.html&agent={"name":"Admin User","mbox":"mailto:scrubbed","objectType":"Agent"}&stateId=http://tincanapi.co.uk/stateapikeys/registrations): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request in Z:\xampp\apps\moodle\htdocs\mod\tincanlaunch\locallib.php on line 501
```

Then I get:

```
The Learning Record Store is not available. Please contact a system administrator.
```

**Comment by garemoko** [comment]
Shame you don't get the error message, still if changing the version to 1.0.0 fixes this, that's pretty clear.

**Comment by davidpesce** [comment]
If you are still of the mindset to remove version from the entire plugin. Then I think testing for this PR is complete on my part. As long as the version is set to 1.0.0 in the admin settings, the changes work flawlessly. Within the activity settings, the version is assumed (hardcoded) to be 1.0.0.

I'd rather submit the removal of the version as a separate PR.

Thoughts?

**Comment by garemoko** [comment]
Always in favour of more and smaller PRs.

**Comment by davidpesce** [comment]
Deal. I'll leave this as is and create a new branch for version hardcoding.

**Comment by garemoko** [comment]
On upgrading I get this: 

image

Have you tried upgrading from the current version in the repo to the version in your master branch?

**Comment by garemoko** [comment]
I think the problem is in db/upgrade.php you need to specify defaults.

**Comment by davidpesce** [comment]
Yeah, the upgrade worked fine for me. Based on your error though, I remember I didn't have any existing tincanlaunch activities created and therefore there wouldn't be anything in the database.

Let me try it and see.

**Comment by davidpesce** [comment]
OK, that works now. Thanks for catching that!

**Comment by nadavkav** [comment]
We should allow each the user to input the LRS xAPI supported version for each activity since users most likly use various LRSes which implement different xAPI versions.
(I am also getting errors using wrong or missing xAPI version when connecting with various LRS vendors)

**Comment by davidpesce** [comment]
@nadavkav are you using the latest branch from my fork? If so, which LRS are you having problems with? Also, does 1.0.0 work for them all?

**Comment by nadavkav** [comment]
Talking the Moodle HQ, I found out I was using recently deprecated event classes so I need to upload a fix for this recently merged issue. Sorry of the mess. So should I start a new merge request?

**Comment by nadavkav** [comment]
@davidpesce nope. These are standalone tests I made to LL and WaxLRS a few weeks ago before this issue came up while I was trying to figure out why and if I needed to pass the version property on each statement.

**Comment by nadavkav** [comment]
I probably missed some of the discussion. What branch are we talking about?

**Comment by nadavkav** [comment]
@davidpesce ok. found that branch :-)

**Comment by davidpesce** [comment]
Seems like according to the spec (or what the xAPI spec should say), v1.0.0 is interpreted the same as 1.0.x. [reference](https://github.com/adlnet/xAPI-Spec/issues/668). 

I hardcoded the version at 1.0.0 and it seems to work with SCORMCloud and LL. Does WaxLRS have a free dev account? It'd be nice to test it across all three when we push out new releases.

**Comment by davidpesce** [comment]
Scratch that, I found the fine print for free developer accounts.

**Comment by nadavkav** [comment]
Thank for that update.
And yes. WaxLRS enables you to open a free developer account for testing. (if you have any issues with them I will give you my credentials)
And... there is also GrassBlade LRS (http://demo.nextsoftwaresolutions.com/grassblade-lrs/users/login)

**Comment by davidpesce** [comment]
Ahhh, beautiful! Thank you!

**Comment by nadavkav** [comment]
It seems like a good time to start thinking on a unit test for those LRSes :-)

**Comment by davidpesce** [comment]
Unit testing, 100% agree!

**Comment by davidpesce** [comment]
@garemoko any headway on testing this?

**Comment by garemoko** [comment]
Sorry; this is likely to be late this week at the earliest for me.

**Comment by davidpesce** [comment]
Sounds good. Keep me posted. I believe I have a few more issues squashed. But I want to wait until the repositories are closer.

**Comment by garemoko** [comment]
Installs great now. Couple of minor points on the Module settings page:
1. I thought we were getting rid of version - is that covered by another PR?
2. Change "Your LRS password key" to "Your LRS password (secret)" (same applies within the instance settings - hopefully this is the same lang string?)

On the instance settings:
Moodle has a specific concept of advanced settings as coming under the various headings (see the SCORM module, for instance) so I don't think we should call that section "advanced". Instead, how about "LRS settings" and add some text and the start to say that by default this uses the global module settings in site admin/plugins/activity modules.

As these are all minor, I'm going to go ahead and merge, and create a new issue to pick these up separately.

**Pull request merged**
