### PR TITLE
updated activity ID

### PR DESCRIPTION
**Pull request by caperneoignis**
added the activity ID to feed in the activity ID into the content. This should resolve issue #150.

### CODE REVIEW

**Comment by caperneoignis** [comment]
@garemoko who do you want to review this? It is a one line update.

**Comment by garemoko** [comment]
@caperneoignis again, this is deleting the language file, which it shouldn't. 

Other than that, the code looks fine so I'm happy to merge this (once the lang file is un-deleted) if somebody else is able to test with a few different authoring tools and confirm no issues, especially if activity id field is left blank.

**Comment by caperneoignis** [comment]
@garemoko The issue is, the copy and paste detection is throwing an error. The language file in question is a build on of Portuguese with no differences, which means you don't need it since it will default to regular Portuguese if it can not find any array elements for the Brazilian variant. I can add it back if you like. But it will start to fail jobs again.

**Comment by garemoko** [comment]
See discussion in #152

**Comment by garemoko** [comment]
Merging. Will test as part of next release.

**Pull request merged**
