### PR TITLE
Add styles.css (to support RTL mode)

### PR DESCRIPTION
**Pull request by nadavkav**

### CODE REVIEW

**Comment by garemoko** [comment]
Hi. Thanks for this. I'll take a proper look later, but it looks like the filename is wrong?

**Comment by nadavkav** [comment]
Great.
(The filename seems ok. Also works fine)

**Comment by garemoko** [comment]
Github is saying the file is called "stayles.css" - it should be styles.css

**Comment by nadavkav** [comment]
oups. me bad.

**Comment by nadavkav** [comment]
renamed to styles.css

**Comment by garemoko** [comment]
Thanks. This looks good now; I just need to make some time to install and test.

**Comment by garemoko** [comment]
I've not had time to test this and I won't do anytime soon. Merging for now; can be reverted if need be.

**Pull request merged**
