### PR TITLE
Fixed Issue #175

### PR DESCRIPTION
**Pull request by abertranb**
Get the user in cron job

### CODE REVIEW

**Comment by wessama** [comment]
Is there a reason this pull request was never merged?

Ref: https://github.com/garemoko/moodle-mod_tincanlaunch/issues/181

**Comment by davidpesce** [comment]
@wessama - I'm taking over this repo and plan on getting things in order. I've got a few other things to get merged in and should be able to take a look at this early next week.

**Comment by davidpesce** [comment]
@abertranb - Thanks for contributing this! can you back out your changes (in this PR) to the two lang files and the version.php? Those shouldn't be changed in this PR.

**Comment by abertranb** [comment]
Yes @davidpesce should be other PR, I will review it

**Comment by davidpesce** [comment]
@abertranb - any word on this? Happy to test/commit this separately if you're booked. We are pushing for a larger release (v2) with all the bugs fixed and new features added.

**Comment by davidpesce** [comment]
Fixed via #196 and #197.

**Pull request closed without merging**
